### ISSUE TITLE
Field regions issues

### ISSUE THREAD

**Issue by Gabriel-p** [asteca/ASteCA#353]
There are multiple possibilities for the field regions. The associated issues to each one are:

1. One or more field regions can be defined.
   - [ ] Create a large number of random field regions #288 
1. A fraction of a field region can be defined.
   - [ ] Generate a field region from a region smaller than the cluster's area #306 
1. Not even a fraction of a field region can be defined (cluster is larger than the frame)
   - [ ] Allow manual field density #296
